import { Course, Faculty, AdmissionLead, Notice, EventItem, ResultStory, StudentProfile, StudyMaterial } from '@/types';
import { MEDIA_REGISTRY } from '@/lib/media/registry';

export const SEED_COURSES: Course[] = [
  {
    id: 'course-1',
    slug: 'advanced-stem-competitive-olympiad-pathway',
    title: 'Advanced STEM & Competitive Olympiad Pathway',
    subtitle: 'Elite coaching program for National & International Olympiads and Top-Tier STEM Entrance Exams',
    category: 'Competitive Exams',
    level: 'Comprehensive',
    duration: '24 Months (2-Year Integrated Cohort)',
    eligibility: 'Class 10 completed or Class 11 enrolled with minimum 75% aggregate in Science and Mathematics, or qualified via NSTHE scholarship assessment.',
    mode: 'Hybrid (Classroom + Live)',
    schedule: 'Mon, Wed, Fri: 4:30 PM - 8:30 PM | Sun: 9:00 AM - 1:00 PM (Mock Exam)',
    certification: 'EduNexa Certificate of Advanced STEM Distinction & Olympiad Fellowship',
    badge: 'Flagship Program',
    rating: 4.95,
    reviewsCount: 382,
    enrolledCount: 1450,
    fee: 3200,
    discountedFee: 2850,
    featured: true,
    active: true,
    thumbnail: MEDIA_REGISTRY.courses.stemOlympiad.url,
    shortDescription: 'A rigorous multi-tiered curriculum designed by former Olympiad rankers and university professors to build foundational mastery in Physics, Advanced Mathematics, Chemistry, and Analytical Thinking.',
    fullDescription: 'The Advanced STEM & Competitive Olympiad Pathway is EduNexa’s premier 2-year integrated coaching program. Engineered from first principles, this cohort is designed specifically for students targeting single-digit national entrance exam ranks and International Science Olympiad (IPhO, IMO, IChO) honors. Students undergo intensive concept deconstruction, multivariable calculus proofs, thermodynamic cycle analysis, and real-time timed test simulations under authentic proctored conditions.',
    highlights: [
      'Daily 1-on-1 twilight problem-solving desks with senior Olympiad medalists',
      'Proprietary 40-volume curriculum and archived 15-year entrance question deconstructions',
      'AI-powered diagnostic gap engine analyzing speed, velocity, and concept retention',
      'Air-conditioned tiered lecture amphitheaters and soundproof personal study cabins',
      'Full scholarship fee waiver eligibility up to 100% via NSTHE benchmark test',
    ],
    learningOutcomes: [
      'Master intuitive problem formulation across Mechanics, Electromagnetism, and Modern Physics',
      'Develop rapid mental heuristics and multivariable calculus proof strategies',
      'Eliminate negative marking errors with predictive velocity analytics',
      'Attain top-tier performance readiness for MIT, Stanford, and National STEM selections',
    ],
    prerequisites: [
      'Solid grasp of Grade 10 Algebra, Geometry, and Basic Trigonometry',
      'High intellectual stamina for multi-hour problem exploration',
    ],
    targetAudience: 'High school students (Grades 11 & 12) aiming for top-100 national ranks & global STEM admissions',
    upcomingBatchDate: '2026-09-15',
    facultyIds: ['fac-1', 'fac-4'],
    syllabus: [
      {
        id: 'mod-1',
        title: 'Foundational Mechanics, Vector Calculus & Kinematics',
        duration: '6 Months',
        lessonsCount: 72,
        topics: [
          'Vector Calculus & Coordinate Systems in 3D',
          'Non-inertial Frames, Coriolis Force & Pseudo-forces',
          'Rotational Dynamics & Moment of Inertia Tensors',
          'Work-Energy-Power & Non-conservative Force Fields',
          'Gravitation & Central Force Celestial Mechanics',
        ],
      },
      {
        id: 'mod-2',
        title: 'Electromagnetism, Wave Optics & Differential Equations',
        duration: '6 Months',
        lessonsCount: 68,
        topics: [
          'Gauss’s Law & Poisson-Laplace Differential Equations',
          'Capacitance & Dielectric Polarization Models',
          'Biot-Savart Law & Ampère’s Circuital Theorem',
          'Faraday Induction & Maxwell’s Electromagnetic Wave Equations',
          'Wave Optics: Interference, Diffraction & Polarization',
        ],
      },
      {
        id: 'mod-3',
        title: 'Advanced Physical & Organic Chemistry Heuristics',
        duration: '6 Months',
        lessonsCount: 64,
        topics: [
          'Quantum Mechanical Model of Atom & Orbital Symmetry',
          'Chemical Thermodynamics & Gibbs Free Energy Criteria',
          'Reaction Mechanisms & Stereochemistry in Carbon Compounds',
          'Electrochemistry & Nernst Equation Applications',
          'Coordination Chemistry & Crystal Field Theory',
        ],
      },
      {
        id: 'mod-4',
        title: 'Full-Syllabus National Test Series & Rank Polish',
        duration: '6 Months',
        lessonsCount: 60,
        topics: [
          '15-Year Archive Comprehensive Question Deconstructions',
          'Olympiad Multi-concept Challenge Papers',
          'Velocity Drills & Time-per-question Management',
          '1-on-1 Diagnostic Performance Consultations',
        ],
      },
    ],
  },
  {
    id: 'course-2',
    slug: 'full-stack-software-engineering-applied-ai',
    title: 'Full-Stack Software Engineering & Applied AI',
    subtitle: 'Professional boot-track for high-impact software careers with direct industry capstones',
    category: 'Engineering & IT',
    level: 'Advanced',
    duration: '9 Months (Weekend + Evening Intensive)',
    eligibility: 'Open to STEM undergraduates, engineering graduates, computer science students, and working professionals looking to transition to tier-1 tech roles.',
    mode: 'Hybrid (Classroom + Live)',
    schedule: 'Tue, Thu: 7:00 PM - 9:30 PM | Sat: 10:00 AM - 4:00 PM (Lab & Capstone)',
    certification: 'EduNexa Senior Full-Stack & Generative AI Systems Engineering Credential',
    badge: 'High Placement Track',
    rating: 4.96,
    reviewsCount: 520,
    enrolledCount: 2180,
    fee: 2400,
    discountedFee: 1999,
    featured: true,
    active: true,
    thumbnail: MEDIA_REGISTRY.courses.softwareAi.url,
    shortDescription: 'Transform into a senior-ready engineer mastering modern web stacks (TypeScript, Next.js, Node.js), distributed cloud systems, generative AI agent orchestration, and system design architectures.',
    fullDescription: 'Crafted in collaboration with staff engineers and engineering managers from Google, Meta, and Stripe, this curriculum bridges academic foundations with production-scale software delivery. You will build distributed microservices, deploy autonomous LLM multi-agent systems, write concurrent cloud pipelines, and practice rigorous technical whiteboard interviews.',
    highlights: [
      '3 Production-grade live client capstone deployments to AWS / GCP',
      'Weekly live code reviews and architecture walkthroughs by FAANG managers',
      'System design drills: high-concurrency caching, rate limiting, and event streaming',
      'Dedicated tech placement desk with 200+ global hiring partners and referral channels',
    ],
    learningOutcomes: [
      'Architect full-stack web applications in TypeScript, Next.js 16, and PostgreSQL',
      'Build resilient microservices with Docker, Kubernetes, gRPC, and Redis',
      'Integrate production LLM agent workflows, RAG pipelines, and vector databases',
      'Clear senior-level system design and algorithmic technical screens',
    ],
    prerequisites: [
      'Basic familiarity with at least one programming language (Python, JavaScript, or C++)',
      'Understanding of elementary data structures (Arrays, Objects, Functions)',
    ],
    targetAudience: 'Aspiring software engineers, CS students, and developers seeking staff/senior tier advancement',
    upcomingBatchDate: '2026-09-20',
    facultyIds: ['fac-3'],
    syllabus: [
      {
        id: 'mod-fs-1',
        title: 'Modern TypeScript, Next.js & Distributed Systems Foundations',
        duration: '3 Months',
        lessonsCount: 36,
        topics: [
          'Advanced TypeScript Types, Generics & Utility Types',
          'Next.js Full-Stack Architecture, Server Actions & Streaming',
          'Database Design, PostgreSQL Indexing & Prisma ORM',
          'RESTful, GraphQL & Type-Safe RPC APIs',
          'Authentication, OAuth 2.0 & Session Security Models',
        ],
      },
      {
        id: 'mod-fs-2',
        title: 'Cloud Infrastructure, Containers & Microservices',
        duration: '3 Months',
        lessonsCount: 36,
        topics: [
          'Docker Containerization & Multi-Stage Builds',
          'Kubernetes Pods, Deployments & Service Meshes',
          'Message Brokers: Kafka & RabbitMQ Event-driven Queues',
          'Redis In-Memory Caching & Distributed Locks',
          'CI/CD Pipelines with GitHub Actions & Infrastructure as Code',
        ],
      },
      {
        id: 'mod-fs-3',
        title: 'Applied Generative AI & Autonomous Agent Orchestration',
        duration: '3 Months',
        lessonsCount: 32,
        topics: [
          'Retrieval-Augmented Generation (RAG) & Vector Embeddings',
          'Multi-Agent Coordination & Function Calling Frameworks',
          'Fine-Tuning, Quantization & Self-Hosted Model Inference',
          'End-to-End Capstone Defense & FAANG Mock Interviews',
        ],
      },
    ],
  },
  {
    id: 'course-3',
    slug: 'pre-med-clinical-excellence-biology-foundation',
    title: 'Pre-Med Clinical Excellence & Biology Foundation',
    subtitle: 'Comprehensive preparation for premier medical school entrance and clinical diagnostics',
    category: 'Medical Sciences',
    level: 'Comprehensive',
    duration: '18 Months',
    eligibility: 'Class 10 completed or Class 11/12 enrolled with Biology as a core subject.',
    mode: 'Classroom Intensive',
    schedule: 'Mon to Thu: 3:30 PM - 7:30 PM | Sat: 8:00 AM - 12:00 PM (Clinical Lab)',
    certification: 'EduNexa Pre-Med Clinical Excellence Diploma & Honors Seal',
    badge: '98% Selection Rate',
    rating: 4.88,
    reviewsCount: 290,
    enrolledCount: 980,
    fee: 3100,
    discountedFee: 2750,
    featured: true,
    active: true,
    thumbnail: MEDIA_REGISTRY.courses.medicalFoundation.url,
    shortDescription: 'Rigorous medical curriculum integrating human anatomy, cellular biochemistry, plant physiology, and medical genetics coupled with interactive 3D virtual dissection labs.',
    fullDescription: 'Led by Cambridge and AIIMS-trained medical faculty, this program prepares pre-med aspirants with an unmatched clinical approach to biology and biochemistry. Students not only memorize biological facts but visualize complex biochemical pathways, physiological feedback loops, and clinical pathologies in our state-of-the-art 3D dissection suite.',
    highlights: [
      '3D Virtual Anatomy & Dissection lab access with holographic organ models',
      'Direct mentoring by practicing senior surgeons & medical researchers',
      'Weekly timed clinical scenario simulation exams with negative marking drills',
      'Dedicated memory technique and rapid taxonomic recall workshops',
    ],
    learningOutcomes: [
      'Develop intuitive mastery across Human Physiology, Genetics, and Cytology',
      'Solve multi-step clinical diagnostic and biological reasoning questions with speed',
      'Attain top 0.5 percentile entrance scores for AIIMS, Harvard Medical, and premier colleges',
    ],
    prerequisites: [
      'Passion for biological sciences and human anatomy',
      'Basic comprehension of cellular structures and basic chemical equations',
    ],
    targetAudience: 'Pre-med students aiming for premier government and Ivy-tier medical universities',
    upcomingBatchDate: '2026-10-01',
    facultyIds: ['fac-2'],
    syllabus: [
      {
        id: 'mod-med-1',
        title: 'Cellular Biology, Biomolecules & Human Physiology',
        duration: '6 Months',
        lessonsCount: 54,
        topics: [
          'Membrane Transport & Mitochondrial Bioenergetics',
          'Cardiovascular & Respiratory Control Systems',
          'Renal Physiology & Osmoregulatory Mechanisms',
          'Neuro-Endocrine Signaling & Synaptic Transmission',
        ],
      },
      {
        id: 'mod-med-2',
        title: 'Molecular Genetics, Inheritance & Biotechnology',
        duration: '6 Months',
        lessonsCount: 50,
        topics: [
          'Mendelian Inheritance & Chromosomal Mapping',
          'DNA Replication, Transcription & Epigenetics',
          'Recombinant DNA Technology & CRISPR Applications',
          'Immunology, Antibody Diversity & Pathogen Evasion',
        ],
      },
    ],
  },
  {
    id: 'course-4',
    slug: 'executive-leadership-business-analytics',
    title: 'Executive Leadership & Business Analytics',
    subtitle: 'Strategic decision-making, predictive analytics, and case study mastery',
    category: 'Management',
    level: 'Intermediate',
    duration: '6 Months',
    eligibility: 'Undergraduates, business professionals, product managers, and executives.',
    mode: 'Live Interactive Online',
    schedule: 'Saturday & Sunday: 9:00 AM - 1:00 PM EST',
    certification: 'EduNexa Executive Business Analytics & Strategic Leadership Certification',
    rating: 4.85,
    reviewsCount: 175,
    enrolledCount: 740,
    fee: 1800,
    discountedFee: 1499,
    featured: false,
    active: true,
    thumbnail: MEDIA_REGISTRY.courses.executiveAnalytics.url,
    shortDescription: 'Master quantitative business modeling, financial strategy, modern AI forecasting, and executive storytelling with Harvard-style business case discussions.',
    fullDescription: 'Designed for ambitious professionals, this executive cohort teaches how to leverage data, predictive modeling, and strategic frameworks to drive multi-million dollar business decisions. Learn directly from former management consultants and CXOs.',
    highlights: [
      '20+ Real-world case study simulations (Harvard & INSEAD case formats)',
      'Executive networking cohorts with alumni CXOs and founders',
      'Hands-on PowerBI, SQL, and Python for predictive business intelligence',
    ],
    learningOutcomes: [
      'Construct financial models and forecast market trends with machine learning',
      'Synthesize complex data into high-stakes executive strategy presentations',
      'Lead digital transformation and AI strategy initiatives within organizations',
    ],
    prerequisites: [
      'Basic numerical literacy and familiarity with spreadsheet software',
    ],
    targetAudience: 'Aspiring product managers, consultants, and business analysts',
    upcomingBatchDate: '2026-09-25',
    facultyIds: ['fac-3'],
    syllabus: [
      {
        id: 'mod-mgmt-1',
        title: 'Strategic Analytics, Financial Modeling & Storytelling',
        duration: '3 Months',
        lessonsCount: 24,
        topics: [
          'Statistical Decision Trees & Regression Models',
          'Corporate Finance, Valuation & Capital Allocation',
          'Executive Dashboard Design in PowerBI & Tableau',
        ],
      },
      {
        id: 'mod-mgmt-2',
        title: 'Predictive Machine Learning & Executive Leadership Capstone',
        duration: '3 Months',
        lessonsCount: 24,
        topics: [
          'Customer Churn & Demand Forecasting in Python',
          'Organizational Change Management & High-Stakes Negotiation',
          'Live CXO Boardroom Capstone Presentation',
        ],
      },
    ],
  },
];

export const SEED_FACULTY: Faculty[] = [
  {
    id: 'fac-1',
    name: 'Dr. Arthur Sterling',
    title: 'Head of Physics & Olympiad Studies',
    department: 'Physical Sciences',
    qualifications: 'Ph.D. in Theoretical Physics, MIT • Former Olympiad Coach',
    experienceYears: 18,
    specialization: ['Classical Mechanics', 'Quantum Electrodynamics', 'Competitive Problem Solving'],
    bio: 'Mentored over 45 International Olympiad gold medalists and 800+ top 100 national rankers over an 18-year distinguished teaching tenure.',
    avatar: MEDIA_REGISTRY.faculty.arthurSterling.url,
    rating: 4.98,
    studentsMentored: 4200,
    email: 'a.sterling@edunexa.edu',
  },
  {
    id: 'fac-2',
    name: 'Dr. Elena Rostova',
    title: 'Dean of Medical & Life Sciences',
    department: 'Biological & Medical Sciences',
    qualifications: 'M.D., Ph.D. in Molecular Genetics, Cambridge',
    experienceYears: 14,
    specialization: ['Human Physiology', 'Gene Expression', 'Bioenergetics'],
    bio: 'Renowned researcher and medical educator dedicated to demystifying complex bio-pathways through visual conceptual models.',
    avatar: MEDIA_REGISTRY.faculty.elenaRostova.url,
    rating: 4.95,
    studentsMentored: 3100,
    email: 'e.rostova@edunexa.edu',
  },
  {
    id: 'fac-3',
    name: 'Prof. Marcus Vance',
    title: 'Director of Computer Science & AI Systems',
    department: 'Engineering & Computing',
    qualifications: 'M.S. in Computer Science, Stanford • Ex-Staff Engineer Google',
    experienceYears: 12,
    specialization: ['Distributed Systems', 'Generative AI Pipelines', 'Cloud Architecture'],
    bio: 'Passionate about bridging academic computer science fundamentals with modern real-world cloud scale architectures and LLM systems.',
    avatar: MEDIA_REGISTRY.faculty.marcusVance.url,
    rating: 4.94,
    studentsMentored: 2850,
    email: 'm.vance@edunexa.edu',
  },
  {
    id: 'fac-4',
    name: 'Prof. Sarah Lin',
    title: 'Senior Faculty in Advanced Mathematics',
    department: 'Mathematical Sciences',
    qualifications: 'Ph.D. in Applied Mathematics, UC Berkeley',
    experienceYears: 10,
    specialization: ['Multivariable Calculus', 'Combinatorics & Number Theory', 'Linear Algebra'],
    bio: 'Specialist in rapid calculation heuristics and conceptual mathematical problem architecture.',
    avatar: MEDIA_REGISTRY.faculty.sarahLin.url,
    rating: 4.92,
    studentsMentored: 2400,
    email: 's.lin@edunexa.edu',
  },
];

export const SEED_NOTICES: Notice[] = [
  {
    id: 'not-1',
    title: 'National Scholarship & Talent Hunt Exam (NSTHE 2026) Announced',
    content: 'Registration is now open for our annual nationwide scholarship test. Top 15% rankers will be awarded up to 100% tuition fee waivers across all 2-year and 1-year coaching cohorts.',
    category: 'Exams',
    targetAudience: 'All',
    publishDate: '2026-08-28',
    isPinned: true,
    author: 'Admissions Board',
  },
  {
    id: 'not-2',
    title: 'Commencement of Fall 2026 Batch Orientation',
    content: 'All enrolled students for STEM Pathway and Software AI cohorts must report to Amphitheater A-102 at 9:30 AM on September 15 for ID card issuance and digital LMS onboarding.',
    category: 'Academic',
    targetAudience: 'Students',
    publishDate: '2026-08-25',
    isPinned: false,
    author: 'Dean of Academics',
  },
];

export const SEED_EVENTS: EventItem[] = [
  {
    id: 'ev-1',
    title: 'High-Performance Problem Solving in Multivariable Calculus',
    subtitle: 'Live interactive masterclass breaking down 10 classic Olympiad challenge problems.',
    type: 'Masterclass',
    date: '2026-09-12',
    time: '5:00 PM – 7:30 PM EST',
    location: 'Amphitheater A-102 & Live Stream',
    mode: 'In-Person',
    speakers: ['Prof. Sarah Lin', 'Dr. Arthur Sterling'],
    registrationUrl: '/admissions',
    seatsLeft: 24,
    thumbnail: MEDIA_REGISTRY.events.problemSolvingMasterclass.url,
  },
  {
    id: 'ev-2',
    title: 'EduNexa National Open Campus & Masterclass Day',
    subtitle: 'Tour the 3D dissection labs, attend faculty demo lectures, and receive free 1-on-1 counseling.',
    type: 'Open House',
    date: '2026-09-18',
    time: '10:00 AM – 3:00 PM EST',
    location: 'Main Academic Quad, Innovation Parkway',
    mode: 'In-Person',
    speakers: ['Dr. Arthur Sterling', 'Dr. Elena Rostova', 'Prof. Marcus Vance'],
    registrationUrl: '/admissions',
    seatsLeft: 60,
    thumbnail: MEDIA_REGISTRY.events.openHouse.url,
  },
];

export const SEED_RESULTS: ResultStory[] = [
  {
    id: 'res-1',
    studentName: 'Julian Thorne',
    examOrGoal: 'International Physics Olympiad (IPhO)',
    rankOrScore: 'All-India Rank 04 & Gold Medal',
    year: '2025',
    courseTaken: 'Advanced STEM Pathway',
    quote: 'The depth of doubt solving at EduNexa is incomparable. Dr. Sterling helped me approach physics with visual intuition rather than brute formulas.',
    avatar: MEDIA_REGISTRY.successStories.julianThorne.url,
    instituteAdmittedTo: 'MIT (Massachusetts Institute of Technology), Class of 2029',
  },
  {
    id: 'res-2',
    studentName: 'Priya Narayanan',
    examOrGoal: 'National Pre-Med Entrance Exam',
    rankOrScore: '715 / 720 • AIR 12',
    year: '2025',
    courseTaken: 'Pre-Med Clinical Excellence',
    quote: 'The 3D virtual anatomy lab and clinical case method made complex biological cycles unforgettable.',
    avatar: MEDIA_REGISTRY.successStories.priyaNarayanan.url,
    instituteAdmittedTo: 'AIIMS (All India Institute of Medical Sciences)',
  },
  {
    id: 'res-3',
    studentName: 'Liam O’Connor',
    examOrGoal: 'Senior Engineering Career Track',
    rankOrScore: 'Placed as L5 Distributed Systems Engineer',
    year: '2025',
    courseTaken: 'Full-Stack Software & Applied AI',
    quote: 'The real-world microservice capstones and FAANG code reviews prepared me far better than any traditional degree.',
    avatar: MEDIA_REGISTRY.successStories.liamOConnor.url,
    instituteAdmittedTo: 'CloudScale Inc. (Senior Systems Architect)',
  },
];

export const SEED_STUDENTS: StudentProfile[] = [
  {
    id: 'stu-1',
    name: 'Aarav Mehta',
    email: 'aarav.mehta@edunexa.student',
    role: 'student',
    studentId: 'EDN-2026-0842',
    batch: 'STEM 2026-28 Batch Alpha',
    phone: '+1 (555) 234-5678',
    guardianName: 'Vikram Mehta',
    enrolledCourseIds: ['course-1'],
    attendanceRate: 96.5,
    overallScore: 92.4,
    badges: ['Top 1% Ranker', 'Olympiad Qualifier', 'Perfect Attendance'],
    createdAt: '2026-08-01',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
  },
];

export const SEED_MATERIALS: StudyMaterial[] = [
  {
    id: 'mat-1',
    courseId: 'course-1',
    courseTitle: 'Advanced STEM & Competitive Olympiad Pathway',
    title: 'Volume 04: Vector Mechanics & Rotational Dynamics Master Problem Bank',
    type: 'PDF Notes',
    fileSize: '14.2 MB',
    url: '#',
    uploadDate: '2026-08-20',
    downloadsCount: 340,
    isLocked: false,
  },
  {
    id: 'mat-2',
    courseId: 'course-2',
    courseTitle: 'Full-Stack Software Engineering & Applied AI',
    title: 'Enterprise Next.js 16 & Microservices System Architecture Blueprint',
    type: 'PDF Notes',
    fileSize: '8.6 MB',
    url: '#',
    uploadDate: '2026-08-22',
    downloadsCount: 512,
    isLocked: false,
  },
];

export const SEED_LEADS: AdmissionLead[] = [
  {
    id: 'lead-1',
    name: 'Maya Patel',
    email: 'maya.patel@gmail.com',
    phone: '+1 (555) 890-1234',
    targetCourseId: 'course-1',
    targetCourseTitle: 'Advanced STEM & Competitive Olympiad Pathway',
    currentEducation: 'Grade 11 High School',
    city: 'Boston, MA',
    preferredMode: 'Hybrid',
    message: 'Interested in taking the NSTHE scholarship diagnostic test this weekend.',
    status: 'New',
    createdAt: '2026-08-30T10:15:00Z',
    notes: ['Parent inquired about hostel accommodations.'],
  },
];

